version: '4.12.0'
services:
  php-apache-environment:
    container_name: php-side
    image: php:8.0-apache
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: video_game_prices
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: video_games
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
      - 9906:3306
    